name: build

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.9"
      - name: Build sdist and wheel
        run: |
          python -m pip install -U build setuptools_scm
          python -m build .
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
