# From github.com/dfm/tinygp
name: tests

on:
  workflow_dispatch:
  schedule:
    # Run on the 13th and 28th of each month, at 00:23 UTC:
    - cron:  '23 00 13,28 * *'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout PyVBMC
        uses: actions/checkout@v3
        with:
          path: pyvbmc

      - name: Checkout GPyReg
        uses: actions/checkout@v3
        with:
          repository: acerbilab/gpyreg
          path: gpyreg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyVBMC
        run: |
          cd ./pyvbmc
          python -m pip install -e .

      - name: Install GPyReg
        run: |
          cd ./gpyreg
          python -m pip install -e .

      - name: Run tests
        run: |
          cd ./pyvbmc
          python -m pytest --reruns=5 -x -vv
